# Build Docker image with CI/CD and push to the GitLab registry.
image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]
before_script:
    - cat $EOELAB_DOMAIN_CERT > /kaniko/ssl/certs/additional-ca-cert-bundle.crt
# up-c-build:
#   stage: build
#   needs: []
#   script:
#     - cd upstream/cpu
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:up-c"
pyjo-c-build:
  stage: build
  needs: [] # up-c-build
  script:
    - cd pyjo/cpu
    - /kaniko/executor
      --context ./
      --dockerfile "Dockerfile"
      --cache=false
      --snapshot-mode=redo
      --destination "ben0i0d/jupyter:pyjo-c"
# scipyjo-c-build:
#   stage: build
#   needs: [pyjo-c-build] # 
#   script:
#     - cd scipyjo/cpu
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:scipyjo-c"
# scrpyjo-c-build:
#   stage: build
#   needs: [pyjo-c-build] # 
#   script:
#     - cd scrpyjo
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --build-arg "http_proxy=http://192.168.2.175:7890"
#       --build-arg "HTTP_PROXY=http://192.168.2.175:7890"
#       --build-arg "https_proxy=http://192.168.2.175:7890"
#       --build-arg "HTTPS_PROXY=http://192.168.2.175:7890"
#       --build-arg "no_proxy=127.0.0.1,localhost,172.0.0.0/8,192.0.0.0/8"
#       --build-arg "NO_PROXY=127.0.0.1,localhost,172.0.0.0/8,192.0.0.0/8"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:scrpyjo-c"
# pyjospark-c-build:
#   stage: build
#   needs: [scipyjo-c-build] # 
#   script:
#     - cd pyjospark
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:pyjospark-c"
# pyjoflink-c-build:
#   stage: build
#   needs: [scipyjo-c-build] # 
#   script:
#     - cd pyjoflink
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:pyjoflink-c"
# pyjoai-c-build:
#   stage: build
#   needs: [scipyjo-c-build] # 
#   script:
#     - cd pyjoai/cpu
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:pyjoai-c"
# llinux-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd llinux
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:llinux-c"
# c-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd c
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:c-c"
# cpp-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd cpp
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:cpp-c"
# fortran-c-build:
#   stage: build
#   needs: [up-c-build]
#   script:
#     - cd fortran
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:fortran-c"
# java-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd java
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:java-c"
# js-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd js
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:js-c"
# kotlin-c-build:
#   stage: build
#   needs: [up-c-build]
#   script:
#     - cd kotlin
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:kotlin-c"
# haskell-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd haskell
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:haskell-c"
# go-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd go
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --build-arg "http_proxy=http://192.168.2.175:7890"
#       --build-arg "HTTP_PROXY=http://192.168.2.175:7890"
#       --build-arg "https_proxy=http://192.168.2.175:7890"
#       --build-arg "HTTPS_PROXY=http://192.168.2.175:7890"
#       --build-arg "no_proxy=127.0.0.1,localhost,172.0.0.0/8,192.0.0.0/8"
#       --build-arg "NO_PROXY=127.0.0.1,localhost,172.0.0.0/8,192.0.0.0/8"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:go-c"
# rust-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd rust
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --build-arg "http_proxy=http://192.168.2.175:7890"
#       --build-arg "HTTP_PROXY=http://192.168.2.175:7890"
#       --build-arg "https_proxy=http://192.168.2.175:7890"
#       --build-arg "HTTPS_PROXY=http://192.168.2.175:7890"
#       --build-arg "no_proxy=127.0.0.1,localhost,172.0.0.0/8,192.0.0.0/8"
#       --build-arg "NO_PROXY=127.0.0.1,localhost,172.0.0.0/8,192.0.0.0/8"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:rust-c"
# julia-c-build:
#   stage: build
#   needs: [up-c-build]
#   script:
#     - cd julia
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:julia-c"
# scir-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd scir
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:scir-c"
# rspark-c-build:
#   stage: build
#   needs: [scir-c-build] # 
#   script:
#     - cd rspark
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:rspark-c"
# agda-c-build:
#   stage: build
#   needs: [up-c-build]
#   script:
#     - cd agda
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:agda-c"
# ansible-c-build:
#   stage: build
#   needs: [up-c-build]
#   script:
#     - cd ansible
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:ansible-c"
# dyalog-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd dyalog
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:dyalog-c"
# cadabra-c-build:
#   stage: build
#   needs: [up-c-build]
#   script:
#     - cd cadabra
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:cadabra-c"
# chapel-c-build:
#   stage: build
#   needs: [up-c-build]
#   script:
#     - cd chapel
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:chapel-c"
# lua-c-build:
#   stage: build
#   needs: [up-c-build]
#   script:
#     - cd lua
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:lua-c"
# sql-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd sql
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:sql-c"
# sage-c-build:
#   stage: build
#   needs: [up-c-build]
#   script:
#     - cd sagemath
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:sage-c"
# dotnet-c-build:
#   stage: build
#   needs: [up-c-build]
#   script:
#     - cd dotnet
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:dotnet-c"
# octave-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd octave
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:octave-c"
# scilab-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd scilab
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:scilab-c"
# mathematica-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd mathematica
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:mathematica-c"
# maple-c-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd maple
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:maple-c"
# matlab-c-minimal-build:
#   stage: build
#   needs: [up-c-build] # 
#   script:
#     - cd matlab/cpu/minimal
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:matlab-c-minimal"
# matlab-c-mcm-build:
#   stage: build
#   needs: [matlab-c-minimal-build] # 
#   script:
#     - cd matlab/cpu/mcm
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:matlab-c-mcm"

# up-g-build:
#   stage: build
#   needs: []
#   script:
#     - cd upstream/gpu
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:up-g"
# pyjo-g-build:
#   stage: build
#   needs: [up-g-build] # 
#   script:
#     - cd pyjo/gpu
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --build-arg "http_proxy=http://192.168.2.175:7890"
#       --build-arg "HTTP_PROXY=http://192.168.2.175:7890"
#       --build-arg "https_proxy=http://192.168.2.175:7890"
#       --build-arg "HTTPS_PROXY=http://192.168.2.175:7890"
#       --build-arg "no_proxy=127.0.0.1,localhost,172.0.0.0/8,192.0.0.0/8"
#       --build-arg "NO_PROXY=127.0.0.1,localhost,172.0.0.0/8,192.0.0.0/8"
#       --cache=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:pyjo-g"
# scipyjo-g-build:
#   stage: build
#   needs: [pyjo-g-build] # 
#   script:
#     - cd scipyjo/gpu
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --build-arg "http_proxy=http://192.168.2.175:7890"
#       --build-arg "HTTP_PROXY=http://192.168.2.175:7890"
#       --build-arg "https_proxy=http://192.168.2.175:7890"
#       --build-arg "HTTPS_PROXY=http://192.168.2.175:7890"
#       --build-arg "no_proxy=127.0.0.1,localhost,172.0.0.0/8,192.0.0.0/8"
#       --build-arg "NO_PROXY=127.0.0.1,localhost,172.0.0.0/8,192.0.0.0/8"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:scipyjo-g"
# pyjoai-g-build:
#   stage: build
#   needs: [scipyjo-g-build] # 
#   script:
#     - cd pyjoai/gpu
#     - /kaniko/executor
#       --context ./
#       --dockerfile "Dockerfile"
#       --cache=false
#       --compressed-caching=false
#       --snapshot-mode=redo
#       --destination "ben0i0d/jupyter:pyjoai-g"